apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        {{- range $svcName, $svc := .Values.services }}
          {{- if $svc.enabled }}
        - name: {{ $svcName }}
          image: {{ $svc.image.repository }}:{{ $svc.tag }}
          ports:
            - containerPort: {{ $svc.port }}
          {{- end }}
        {{- end }}
