{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      nodePort: {{ $svc.nodePort }}
---
{{- end }}
{{- end }}
