spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  sql:
    init:
      mode: always
      data-locations: classpath:db/mysql/data.sql
      schema-locations: classpath:db/mysql/schema.sql

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://mysql:3306/petclinic
    username: root
    password: root