spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://mysql:3306/petclinic
    username: admin
    password: petclinic