apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 8090

  - host: customers.petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customers-service
            port:
              number: 8081

  - host: visits.petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visits-service
            port:
              number: 8082

  - host: vets.petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vets-service
            port:
              number: 8083

  - host: genai.petclinic.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genai-service
            port:
              number: 8084
