spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://mysql.petclinic.svc.cluster.local:3306/petclinic
    username: root
    password: petclinic
    driver-class-name: com.mysql.cj.jdbc.Driver