apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-petclinic-project
  namespace: argocd
spec:
  description: Quản lý các ứng dụng của spring-petclinic (dev & staging)
  
  sourceRepos:
    - https://github.com/22127063/spring-petclinic-microservices.git
  
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
