spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  sql:
    init:
      mode: always
      data-locations: classpath:db/mysql/data.sql
      schema-locations: classpath:db/mysql/schema.sql

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
