apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-staging
  namespace: argocd
spec:
  project: spring-petclinic-project
  source:
    repoURL: https://github.com/22127063/spring-petclinic-microservices.git
    path: petclinic-chart/
    targetRevision: main
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
