apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: 22127063/spring-petclinic-admin-server:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: admin-server
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 30990