apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      tier: config-server
  template:
    metadata:
      labels:
        app: petclinic
        tier: config-server
    spec:
      containers:
        - name: app
          image: 22127063/spring-petclinic-config-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: database
          ports:
            - name: http
              containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: petclinic
spec:
  type: NodePort
  selector:
     app: petclinic
     tier: config-server
  ports:
    - port: 8888
      targetPort: 8080
      nodePort: 30088