apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: 22127063/spring-petclinic-customers-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: customers-config
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  type: NodePort
  selector:
    app: customers
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081