apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-deployment
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai
  template:
    metadata:
      labels:
        app: genai
    spec:
      containers:
        - name: genai
          image: 22127063/spring-petclinic-genai-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: genai
  ports:
    - port: 8084
      targetPort: 8080
      nodePort: 30084