apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      tier: genai
  template:
    metadata:
      labels:
        app: petclinic
        tier: genai
    spec:
      containers:
        - name: app
          image: 22127063/spring-petclinic-genai-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: database
          ports:
            - name: http
              containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: genai
  namespace: petclinic
spec:
  type: NodePort
  selector:
     app: petclinic
     tier: genai
  ports:
    - port: 8084
      targetPort: 8080
      nodePort: 30084