apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      tier: vets
  template:
    metadata:
      labels:
        app: petclinic
        tier: vets
    spec:
      containers:
        - name: app
          image: 22127063/spring-petclinic-vets-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: database
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: pdb-mysql
          ports:
            - name: http
              containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: vets
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
    tier: vets
  ports:
    - port: 8083
      targetPort: 8080
      nodePort: 30083