apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-deployment
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
        - name: vets
          image: 22127063/spring-petclinic-vets-service:latest
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: vets
  ports:
    - port: 8083
      targetPort: 8080
      nodePort: 30083