apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      tier: visits
  template:
    metadata:
      labels:
        app: petclinic
      tier: visits
    spec:
      containers:
        - name: app
          image: 22127063/spring-petclinic-visits-service:latest
          magePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: database
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: pdb-mysql
          ports:
            - name: http
              containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: visits
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
    tier: visits
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30082