apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: petclinic
  labels:
    app: api-gateway
data:
  CUSTOMERS_SERVICE_URL: "http://customers-service:8081"
  VISITS_SERVICE_URL: "http://visits-service:8082"
  VETS_SERVICE_URL: "http://vets-service:8083"
